#!/bin/sh

stow alacritty neovim tmux


# Setup vscode
ln -s "$(pwd)/code/settings.json" ~/Library/Application\ Support/Code/User

for extension in $(jq -r ".[]" < code/extensions.json); do 
    code --install-extension "$extension"
done